// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LotSelector struct {
	Cursor               uint64   `protobuf:"varint,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit                uint32   `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LotSelector) Reset()         { *m = LotSelector{} }
func (m *LotSelector) String() string { return proto.CompactTextString(m) }
func (*LotSelector) ProtoMessage()    {}
func (*LotSelector) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_fcf5ed6749cd5e28, []int{0}
}
func (m *LotSelector) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LotSelector.Unmarshal(m, b)
}
func (m *LotSelector) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LotSelector.Marshal(b, m, deterministic)
}
func (dst *LotSelector) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LotSelector.Merge(dst, src)
}
func (m *LotSelector) XXX_Size() int {
	return xxx_messageInfo_LotSelector.Size(m)
}
func (m *LotSelector) XXX_DiscardUnknown() {
	xxx_messageInfo_LotSelector.DiscardUnknown(m)
}

var xxx_messageInfo_LotSelector proto.InternalMessageInfo

func (m *LotSelector) GetCursor() uint64 {
	if m != nil {
		return m.Cursor
	}
	return 0
}

func (m *LotSelector) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type LotPage struct {
	Lot                  *Lot                    `protobuf:"bytes,1,opt,name=lot,proto3" json:"lot,omitempty"`
	Participants         map[uint64]*Participant `protobuf:"bytes,2,rep,name=participants,proto3" json:"participants,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *LotPage) Reset()         { *m = LotPage{} }
func (m *LotPage) String() string { return proto.CompactTextString(m) }
func (*LotPage) ProtoMessage()    {}
func (*LotPage) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_fcf5ed6749cd5e28, []int{1}
}
func (m *LotPage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LotPage.Unmarshal(m, b)
}
func (m *LotPage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LotPage.Marshal(b, m, deterministic)
}
func (dst *LotPage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LotPage.Merge(dst, src)
}
func (m *LotPage) XXX_Size() int {
	return xxx_messageInfo_LotPage.Size(m)
}
func (m *LotPage) XXX_DiscardUnknown() {
	xxx_messageInfo_LotPage.DiscardUnknown(m)
}

var xxx_messageInfo_LotPage proto.InternalMessageInfo

func (m *LotPage) GetLot() *Lot {
	if m != nil {
		return m.Lot
	}
	return nil
}

func (m *LotPage) GetParticipants() map[uint64]*Participant {
	if m != nil {
		return m.Participants
	}
	return nil
}

type LotsPage struct {
	Lots                 []*Lot                  `protobuf:"bytes,1,rep,name=lots,proto3" json:"lots,omitempty"`
	Participants         map[uint64]*Participant `protobuf:"bytes,2,rep,name=participants,proto3" json:"participants,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *LotsPage) Reset()         { *m = LotsPage{} }
func (m *LotsPage) String() string { return proto.CompactTextString(m) }
func (*LotsPage) ProtoMessage()    {}
func (*LotsPage) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_fcf5ed6749cd5e28, []int{2}
}
func (m *LotsPage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LotsPage.Unmarshal(m, b)
}
func (m *LotsPage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LotsPage.Marshal(b, m, deterministic)
}
func (dst *LotsPage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LotsPage.Merge(dst, src)
}
func (m *LotsPage) XXX_Size() int {
	return xxx_messageInfo_LotsPage.Size(m)
}
func (m *LotsPage) XXX_DiscardUnknown() {
	xxx_messageInfo_LotsPage.DiscardUnknown(m)
}

var xxx_messageInfo_LotsPage proto.InternalMessageInfo

func (m *LotsPage) GetLots() []*Lot {
	if m != nil {
		return m.Lots
	}
	return nil
}

func (m *LotsPage) GetParticipants() map[uint64]*Participant {
	if m != nil {
		return m.Participants
	}
	return nil
}

type Lot struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Participants         []uint64 `protobuf:"varint,2,rep,packed,name=participants,proto3" json:"participants,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Lot) Reset()         { *m = Lot{} }
func (m *Lot) String() string { return proto.CompactTextString(m) }
func (*Lot) ProtoMessage()    {}
func (*Lot) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_fcf5ed6749cd5e28, []int{3}
}
func (m *Lot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lot.Unmarshal(m, b)
}
func (m *Lot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lot.Marshal(b, m, deterministic)
}
func (dst *Lot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lot.Merge(dst, src)
}
func (m *Lot) XXX_Size() int {
	return xxx_messageInfo_Lot.Size(m)
}
func (m *Lot) XXX_DiscardUnknown() {
	xxx_messageInfo_Lot.DiscardUnknown(m)
}

var xxx_messageInfo_Lot proto.InternalMessageInfo

func (m *Lot) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Lot) GetParticipants() []uint64 {
	if m != nil {
		return m.Participants
	}
	return nil
}

type Participant struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId            string   `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	LotId                uint64   `protobuf:"varint,3,opt,name=lot_id,json=lotId,proto3" json:"lot_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Participant) Reset()         { *m = Participant{} }
func (m *Participant) String() string { return proto.CompactTextString(m) }
func (*Participant) ProtoMessage()    {}
func (*Participant) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_fcf5ed6749cd5e28, []int{4}
}
func (m *Participant) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Participant.Unmarshal(m, b)
}
func (m *Participant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Participant.Marshal(b, m, deterministic)
}
func (dst *Participant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Participant.Merge(dst, src)
}
func (m *Participant) XXX_Size() int {
	return xxx_messageInfo_Participant.Size(m)
}
func (m *Participant) XXX_DiscardUnknown() {
	xxx_messageInfo_Participant.DiscardUnknown(m)
}

var xxx_messageInfo_Participant proto.InternalMessageInfo

func (m *Participant) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Participant) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *Participant) GetLotId() uint64 {
	if m != nil {
		return m.LotId
	}
	return 0
}

func init() {
	proto.RegisterType((*LotSelector)(nil), "grcp_demo.LotSelector")
	proto.RegisterType((*LotPage)(nil), "grcp_demo.LotPage")
	proto.RegisterMapType((map[uint64]*Participant)(nil), "grcp_demo.LotPage.ParticipantsEntry")
	proto.RegisterType((*LotsPage)(nil), "grcp_demo.LotsPage")
	proto.RegisterMapType((map[uint64]*Participant)(nil), "grcp_demo.LotsPage.ParticipantsEntry")
	proto.RegisterType((*Lot)(nil), "grcp_demo.Lot")
	proto.RegisterType((*Participant)(nil), "grcp_demo.Participant")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HorizonClient is the client API for Horizon service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HorizonClient interface {
	GetLots(ctx context.Context, in *LotSelector, opts ...grpc.CallOption) (*LotsPage, error)
}

type horizonClient struct {
	cc *grpc.ClientConn
}

func NewHorizonClient(cc *grpc.ClientConn) HorizonClient {
	return &horizonClient{cc}
}

func (c *horizonClient) GetLots(ctx context.Context, in *LotSelector, opts ...grpc.CallOption) (*LotsPage, error) {
	out := new(LotsPage)
	err := c.cc.Invoke(ctx, "/grcp_demo.Horizon/GetLots", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HorizonServer is the server API for Horizon service.
type HorizonServer interface {
	GetLots(context.Context, *LotSelector) (*LotsPage, error)
}

func RegisterHorizonServer(s *grpc.Server, srv HorizonServer) {
	s.RegisterService(&_Horizon_serviceDesc, srv)
}

func _Horizon_GetLots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LotSelector)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HorizonServer).GetLots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grcp_demo.Horizon/GetLots",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HorizonServer).GetLots(ctx, req.(*LotSelector))
	}
	return interceptor(ctx, in, info, handler)
}

var _Horizon_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grcp_demo.Horizon",
	HandlerType: (*HorizonServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLots",
			Handler:    _Horizon_GetLots_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_api_fcf5ed6749cd5e28) }

var fileDescriptor_api_fcf5ed6749cd5e28 = []byte{
	// 347 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xc4, 0x52, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x25, 0x4d, 0x9a, 0x9a, 0x89, 0x16, 0x1d, 0xb5, 0x94, 0x82, 0x50, 0x82, 0x82, 0x07, 0xc9,
	0xa1, 0x82, 0xf8, 0x71, 0x52, 0x10, 0x5b, 0xf0, 0x50, 0xd2, 0x83, 0xe0, 0xa5, 0xac, 0xc9, 0x52,
	0x16, 0xd3, 0x6c, 0xd8, 0x6c, 0x85, 0xfa, 0x23, 0x3d, 0xf8, 0x8b, 0x9c, 0xa4, 0x51, 0x12, 0x9a,
	0xbb, 0xb7, 0x9d, 0x99, 0xf7, 0xde, 0xbe, 0x37, 0x0c, 0x38, 0x2c, 0x15, 0x7e, 0xaa, 0xa4, 0x96,
	0xe8, 0x2c, 0x54, 0x98, 0xce, 0x23, 0xbe, 0x94, 0xde, 0x1d, 0xb8, 0xcf, 0x52, 0xcf, 0x78, 0xcc,
	0x43, 0x2d, 0x15, 0xf6, 0xc0, 0x0e, 0x57, 0x2a, 0x93, 0xaa, 0x6f, 0x0c, 0x8d, 0x73, 0x2b, 0x28,
	0x2b, 0x3c, 0x82, 0x76, 0x2c, 0x96, 0x42, 0xf7, 0x5b, 0xd4, 0xde, 0x0b, 0x36, 0x85, 0xf7, 0x65,
	0x40, 0x87, 0xd8, 0x53, 0xb6, 0xe0, 0x38, 0x04, 0x33, 0x96, 0xba, 0xa0, 0xb9, 0xa3, 0xae, 0xff,
	0xf7, 0x83, 0x4f, 0x80, 0x20, 0x1f, 0xe1, 0x18, 0x76, 0x53, 0xa6, 0xb4, 0x08, 0x45, 0xca, 0x12,
	0x9d, 0x91, 0x94, 0x49, 0xd0, 0xd3, 0x3a, 0x34, 0xd7, 0xf2, 0xa7, 0x15, 0xd8, 0x63, 0xa2, 0xd5,
	0x3a, 0xa8, 0x31, 0x07, 0x2f, 0x70, 0xb0, 0x05, 0xc1, 0x7d, 0x30, 0xdf, 0xf9, 0xba, 0xf4, 0x9d,
	0x3f, 0xf1, 0x02, 0xda, 0x1f, 0x2c, 0x5e, 0xf1, 0xc2, 0xb4, 0x3b, 0xea, 0x55, 0x7e, 0xaa, 0xd0,
	0x83, 0x0d, 0xe8, 0xb6, 0x75, 0x6d, 0x78, 0xdf, 0x06, 0xec, 0x90, 0x89, 0xac, 0x48, 0xe4, 0x81,
	0x45, 0xb6, 0x33, 0x52, 0x34, 0x1b, 0x22, 0x15, 0x33, 0x9c, 0x34, 0x66, 0x3a, 0xab, 0x63, 0xb3,
	0xff, 0x0d, 0x75, 0x03, 0x26, 0x99, 0xc0, 0x2e, 0xb4, 0x44, 0x54, 0x2a, 0xd1, 0x8b, 0xe2, 0x6d,
	0x5b, 0xb7, 0xea, 0x9e, 0xbc, 0x19, 0xb8, 0x15, 0xd1, 0x2d, 0x89, 0x13, 0x00, 0x16, 0x86, 0x72,
	0x95, 0xe8, 0x39, 0xf5, 0x73, 0x43, 0x4e, 0xe0, 0x94, 0x9d, 0x49, 0x84, 0xc7, 0x60, 0xd3, 0x92,
	0xf2, 0x91, 0x59, 0x50, 0xda, 0x54, 0x4d, 0xa2, 0xd1, 0x3d, 0x74, 0xc6, 0x52, 0x89, 0x4f, 0x99,
	0xe0, 0x15, 0x74, 0x9e, 0xb8, 0xce, 0x57, 0x84, 0xbd, 0xfa, 0xce, 0x7e, 0x2f, 0x72, 0x70, 0xd8,
	0xb0, 0xcb, 0x07, 0xfb, 0xd5, 0x5a, 0x32, 0x91, 0xbc, 0xd9, 0xc5, 0x3d, 0x5f, 0xfe, 0x04, 0x00,
	0x00, 0xff, 0xff, 0xd9, 0x3c, 0x36, 0x1f, 0xdc, 0x02, 0x00, 0x00,
}
